name: AIX build
"on":
  push:
    branches:
      - aix-build-test
jobs:
  build-on-aix:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt install wget python3
    - name: Download build script
      run: |
        wget https://raw.githubusercontent.com/bzEq/rust/aix-build-test/src/ci/scripts/run-build-on-aix.py
    - name: Build remotely
      run: |
        python3 ./run-build-on-aix.py
